Vagrant.configure("2") do |config|

config.vm.provider "virtualbox" do |vb|
  vb.name = "MAQUINA-VAGRANT-01"
  vb.memory = 1050
  vb.cpus = 3
end
  
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8090
  config.vm.network "public_network", ip: "192.168.10.100", bridge:"Intel(R) Wireless-AC 9560"
  config.vm.provision "shell", path: "script.sh"
  config.vm.synced_folder "site/" , "/var/www/html"

  #config.vm.provision "ansible" do |ansible|
   # ansible.playbook = "playbook.yml"
end
